language: java
jdk:
  - openjdk8
os:
  - linux
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --activate-profiles coveralls
script:
  - mvn clean test jacoco:report coveralls:report --batch-mode --activate-profiles coveralls -DrepoToken=${COVERALLS_REPO_TOKEN}
